#! /bin/sh


#### START #####
# Start hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd & #

# Fix cursor
xsetroot -cursor_name left_ptr &

# Make keyboard cursor go faster 
xset r rate 210 40

# Start polybar
/home/caioc/.config/polybar/launch_polybar.sh &

# Monitor config
xrandr --output DP-0 --mode 1920x1080 --rate 165.00

# Disable screen saving
xset s off
xset -dpms
xset s noblank

bspc config focus_follows_pointer true

# Set environment variables
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"
export QT_STYLE_OVERRIDE=kvantum

# Polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
xwallpaper --zoom .config/wallpaper.png

# Set keyboard
setxkbmap -layout us,us -variant intl, -option grp:alt_shift_toggle

#### MONITORS ####
bspc monitor DP-0 -d 1 2 3 4 5 6
#bspc monitor HDMI-0 -d 5 6 7 8

#### BSPWM CONFIGURATION ####
bspc config border_width         2
bspc config window_gap           7 
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false
bspc config ignore_ewmh_focus    true

#### BSPWM COLORING ####
bspc config focused_border_color             "#1E3888"

#### RULES ####
bspc rule -a discord focus=off desktop=6
